# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x05hello\"\x14\n\x12SuggestionsRequest\"y\n\x13SuggestionsResponse\x12\x34\n\x05\x62ooks\x18\x01 \x03(\x0b\x32%.hello.SuggestionsResponse.BooksEntry\x1a,\n\nBooksEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32_\n\x12SuggestionsService\x12I\n\x10SuggestionsLogic\x12\x19.hello.SuggestionsRequest\x1a\x1a.hello.SuggestionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUGGESTIONSRESPONSE_BOOKSENTRY']._options = None
  _globals['_SUGGESTIONSRESPONSE_BOOKSENTRY']._serialized_options = b'8\001'
  _globals['_SUGGESTIONSREQUEST']._serialized_start=28
  _globals['_SUGGESTIONSREQUEST']._serialized_end=48
  _globals['_SUGGESTIONSRESPONSE']._serialized_start=50
  _globals['_SUGGESTIONSRESPONSE']._serialized_end=171
  _globals['_SUGGESTIONSRESPONSE_BOOKSENTRY']._serialized_start=127
  _globals['_SUGGESTIONSRESPONSE_BOOKSENTRY']._serialized_end=171
  _globals['_SUGGESTIONSSERVICE']._serialized_start=173
  _globals['_SUGGESTIONSSERVICE']._serialized_end=268
# @@protoc_insertion_point(module_scope)
