scrape_configs:
  - job_name: PrometheusService
    scrape_interval: 5s
    static_configs:
      - targets: [host.docker.internal:9464]

remote_write:
  - url: http://observability:4318/v1/metrics
    basic_auth:
      username: admin
      password: admin