# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x05hello\".\n\x0c\x46raudRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\r\n\x05newVC\x18\x02 \x03(\x05\"Q\n\x12\x46raudThreadRequest\x12\x14\n\x0c\x63reditCardNr\x18\x01 \x01(\t\x12\x10\n\x08userName\x18\x02 \x01(\t\x12\x13\n\x0buserContact\x18\x03 \x01(\t\"?\n\rFraudResponse\x12\x0f\n\x07verdict\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\r\n\x05\x62ooks\x18\x03 \x01(\t2\xd9\x01\n\x0c\x46raudService\x12L\n\x19startFraudDecMicroService\x12\x19.hello.FraudThreadRequest\x1a\x14.hello.FraudResponse\x12;\n\x0euserDataEventC\x12\x13.hello.FraudRequest\x1a\x14.hello.FraudResponse\x12>\n\x11\x63readitCardEventE\x12\x13.hello.FraudRequest\x1a\x14.hello.FraudResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAUDREQUEST']._serialized_start=32
  _globals['_FRAUDREQUEST']._serialized_end=78
  _globals['_FRAUDTHREADREQUEST']._serialized_start=80
  _globals['_FRAUDTHREADREQUEST']._serialized_end=161
  _globals['_FRAUDRESPONSE']._serialized_start=163
  _globals['_FRAUDRESPONSE']._serialized_end=226
  _globals['_FRAUDSERVICE']._serialized_start=229
  _globals['_FRAUDSERVICE']._serialized_end=446
# @@protoc_insertion_point(module_scope)
