# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import books_database_pb2 as books__database__pb2


class DatabaseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.readDatabase = channel.unary_unary(
                '/hello.DatabaseService/readDatabase',
                request_serializer=books__database__pb2.DatabaseReadRequest.SerializeToString,
                response_deserializer=books__database__pb2.DatabaseReadResponse.FromString,
                )
        self.writeDatabase = channel.unary_unary(
                '/hello.DatabaseService/writeDatabase',
                request_serializer=books__database__pb2.DatabaseWriteRequest.SerializeToString,
                response_deserializer=books__database__pb2.DatabaseWriteResponse.FromString,
                )


class DatabaseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def readDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def writeDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'readDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.readDatabase,
                    request_deserializer=books__database__pb2.DatabaseReadRequest.FromString,
                    response_serializer=books__database__pb2.DatabaseReadResponse.SerializeToString,
            ),
            'writeDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.writeDatabase,
                    request_deserializer=books__database__pb2.DatabaseWriteRequest.FromString,
                    response_serializer=books__database__pb2.DatabaseWriteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hello.DatabaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DatabaseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def readDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hello.DatabaseService/readDatabase',
            books__database__pb2.DatabaseReadRequest.SerializeToString,
            books__database__pb2.DatabaseReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def writeDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hello.DatabaseService/writeDatabase',
            books__database__pb2.DatabaseWriteRequest.SerializeToString,
            books__database__pb2.DatabaseWriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
