# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment_system.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14payment_system.proto\x12\x05hello\"!\n\x0ePaymentRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\"\"\n\x0fPaymentResponse\x12\x0f\n\x07verdict\x18\x01 \x01(\t2O\n\x0ePaymentService\x12=\n\x0cpaymentLogic\x12\x15.hello.PaymentRequest\x1a\x16.hello.PaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_system_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PAYMENTREQUEST']._serialized_start=31
  _globals['_PAYMENTREQUEST']._serialized_end=64
  _globals['_PAYMENTRESPONSE']._serialized_start=66
  _globals['_PAYMENTRESPONSE']._serialized_end=100
  _globals['_PAYMENTSERVICE']._serialized_start=102
  _globals['_PAYMENTSERVICE']._serialized_end=181
# @@protoc_insertion_point(module_scope)
