# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_executor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_executor.proto\x12\x05hello\"\x1e\n\x0f\x45xecutorRequest\x12\x0b\n\x03var\x18\x01 \x01(\t\" \n\x10\x45xecutorResponse\x12\x0c\n\x04var2\x18\x01 \x01(\t2K\n\x0f\x45xecutorService\x12\x38\n\x05\x66unc1\x12\x16.hello.ExecutorRequest\x1a\x17.hello.ExecutorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXECUTORREQUEST']._serialized_start=31
  _globals['_EXECUTORREQUEST']._serialized_end=61
  _globals['_EXECUTORRESPONSE']._serialized_start=63
  _globals['_EXECUTORRESPONSE']._serialized_end=95
  _globals['_EXECUTORSERVICE']._serialized_start=97
  _globals['_EXECUTORSERVICE']._serialized_end=172
# @@protoc_insertion_point(module_scope)
