# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_executor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_executor.proto\x12\x05hello\"\x11\n\x0f\x45xecutorRequest\"#\n\x10\x45xecutorResponse\x12\x0f\n\x07verdict\x18\x01 \x01(\t2R\n\x0f\x45xecutorService\x12?\n\x0c\x64\x65queueOrder\x12\x16.hello.ExecutorRequest\x1a\x17.hello.ExecutorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXECUTORREQUEST']._serialized_start=31
  _globals['_EXECUTORREQUEST']._serialized_end=48
  _globals['_EXECUTORRESPONSE']._serialized_start=50
  _globals['_EXECUTORRESPONSE']._serialized_end=85
  _globals['_EXECUTORSERVICE']._serialized_start=87
  _globals['_EXECUTORSERVICE']._serialized_end=169
# @@protoc_insertion_point(module_scope)
